# Generated by Django 2.2.6 on 2019-11-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=20)),
                ('time', models.CharField(default='Wed-15:00-18:20', max_length=20)),
                ('credit', models.IntegerField(default=4)),
                ('faculty', models.CharField(default='IT', max_length=10)),
                ('grade', models.IntegerField(default=1)),
                ('category', models.CharField(default='C', max_length=2)),
                ('classroom', models.CharField(default='C408', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('faculty', models.CharField(default='IT', max_length=20)),
                ('grade', models.IntegerField(default=1)),
                ('password', models.CharField(default='123456', max_length=10)),
            ],
        ),
    ]
