# Generated by Django 2.2.6 on 2019-11-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='sid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
