# Generated by Django 2.2.6 on 2019-11-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusModel', '0002_auto_20191116_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
