# Generated by Django 2.2.6 on 2019-11-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusModel', '0003_auto_20191116_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_course',
            fields=[
                ('sid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=10)),
            ],
        ),
    ]
