# Generated by Django 2.2.6 on 2019-11-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampusModel', '0004_student_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_course',
        ),
    ]
