# Generated by Django 2.2.6 on 2019-11-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampusModel', '0006_student_select'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_select',
        ),
    ]
