# Generated by Django 2.2.6 on 2019-11-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampusModel', '0008_student_select'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student_select',
            unique_together={('sid', 'cid')},
        ),
    ]
